formats:
  datetime_format: "%Y-%m-%d %H:%M:%S"
  datetime_formats:
    # Add your custom datetime formats here
    - "%Y-%m-%dT%H:%M:%S.%f"
    - "%Y-%m-%d %H:%M:%S"
    - "%Y/%m/%d %H:%M:%S"
    - "%Y/%m/%d %H:%M"

  decimal_places:
    # Number of decimal places to round to for each format
    mercator: 4
    geodetic: 10

spatial_coordinates_system:
  # Specify the spatial coordinate system
  JGD2011_R:
    JPN1: 6669
    JPN2: 6670
    JPN3: 6671
    JPN4: 6672
    JPN5: 6673
    JPN6: 6674
    JPN7: 6675
    JPN8: 6676
    JPN9: 6677
    JPN10: 6678
    JPN11: 6679
    JPN12: 6680
    JPN13: 6681
    JPN14: 6682
    JPN15: 6683
    JPN16: 6684
    JPN17: 6685
    JPN18: 6686
    JPN19: 6687
    UTM51: 6688
    UTM52: 6689
    UTM53: 6690
    UTM54: 6691
    UTM55: 6692

columns:
  use_cols_en:
    # Specify the columns to be used
    - "sort_index"
    - "start"
    - "end"
    - "point_name"
    - "point_number"
    - "longitude"
    - "latitude"
    - "altitude"
    - "ellipsoid_height"
    - "geoid_height"
    - "antenna_height"
    - "fix"
    - "fix_mode"
    - "epochs"
    - "interval"
    - "pdop"
    - "number_of_satellites"
    - "std_h"
    - "std_v"
    - "signals"
    - "signal_frequencies"
    - "receiver"
    - "antenna"
    - "jgd"
    - "epsg"
    - "transformed_y"
    - "transformed_x"
  
  add_cols_en:
    - "office"
    - "branch_office"
    - "local_area"
    - "address"
    - "project_year"
    - "project_name"
    - "surveyor"
    - "group_name"
    - "point"
    - "label"
    - "point_size"
  
  selects:
    sort_index: "sort_index"
    start: "start"
    end: "end"
    group_name: "group_name"
    point: "point"
    point_name: "point_name"
    point_number: "point_number"
    longitude: "longitude"
    latitude: "latitude"
    altitude: "altitude"
    pdop: "pdop"
    number_of_satellites: "number_of_satellites"
    signal_frequencies: "signal_frequencies"


  drogger_gps:
    # Specify the column names for each data source of Droger-GPS
    ele: 
      en: "altitude"
      jp: "標高"
    ellipsoidHeight:
      en: "ellipsoid_height"
      jp: "楕円体高"
    geoidheight: 
      en: "geoid_height"
      jp: "ジオイド高"
    name:
      en: "point_name"
      jp: "測点名"
    lon:
      en: "longitude"
      jp: "経度"
    lat:
      en: "latitude"
      jp: "緯度"
    sat:
      en: "number_of_satellites"
      jp: "衛星数"
    hdop:
      en: "pdop"
      jp: "PDOP"
    vdop:
      en: "vdop"
      jp: "VDOP"
    pdop:
      en: "pdop"
      jp: "PDOP"
    pointNumber:
      en: "point_number"
      jp: "測点番号"
    coordGenaration:
      en: "jgd"
      jp: "平面直角座標系"
    type:
      en: "epsg"
      jp: "EPSG"
    y:
      en: "transformed_y"
      jp: "補正後Y"
    x:
      en: "transformed_x"
      jp: "補正後X"
    starttime:
      en: "start"
      jp: "開始"
    endtime:
      en: "end"
      jp: "終了"
    epochs:
      en: "epochs"
      jp: "測定回数"
    epochInterval:
      en: "interval"
      jp: "測定間隔"
    stddevDistanceMeter:
      en: "std_h"
      jp: "水平方向標準偏差"
    stddevHeightMeter:
      en: "std_v"
      jp: "鉛直方向標準偏差"
    fix:
      en: "fix"
      jp: "Fix"
    fixMode:
      en: "fix_mode"
      jp: "Fixモード"
    antennaHeightMesure:
      en: "antenna_height"
      jp: "アンテナ高"
    signals:
      en: "signals"
      jp: "衛星信号"
    receiverName:
      en: "receiver"
      jp: "受信機"
    antennaType:
      en: "antenna"
      jp: "アンテナ"
  
  gyoroman_gg_csv:
    # Specify the column names for each data source of Gyoroman GG
    Nod:
      en: "point_name"
      jp: "測点名"
    INDX:
      en: "point_number"
      jp: "測点番号"
    LAT:
      en: "latitude"
      jp: "緯度"
    LON:
      en: "longitude"
      jp: "経度"
    HEIGHT:
      en: "altitude"
      jp: "標高"
    SYSTIME:
      en: "end"
      jp: "終了"
    GEOIDH:
      en: "geoid_height"
      jp: "ジオイド高"
    SATN:
      en: "number_of_satellites"
      jp: "衛星数"
    PDOP:
      en: "pdop"
      jp: "PDOP"
    HDOP:
      en: "hdop"
      jp: "HDOP"
    VDOP:
      en: "vdop"
      jp: "vdop"
    DATAN:
      en: "epochs"
      jp: "測定回数"
    RMSX:
      en: "std_h"
      jp: "水平方向標準偏差"
    RMSY:
      en: "std_v"
      jp: "鉛直方向標準偏差"
    

satellites:
  signals:
    - "L1" # カーナビやスマホなどの一般的なGPS
    - "L2" # 電離層遅延の計算に必要なデータ
    - "L5" # 新しい人工衛星に搭載されている方式。QZSS
    - "L6" # 日本のGPS衛星「みちびき」に搭載されている方式。cm級の補強する信号。
    
    
    
    
    






