# 全体で使用する列名の設定ファイル。
# 列名を変更したい場合は、ここで変更する。
default:
  sort_index:
    en: "sort_index"
    jp: "sort_index"

  start:
    drg-gps: "starttime"
    en: "start"
    jp: "開始"

  end:
    drg-gps: "endtime"
    gyoroman-gg: "SYSTIME"
    en: "end"
    jp: "終了"

  point:
    en: "point"
    jp: "測点"

  point_name:
    drg-gps: "name"
    gyoroman-gg: "Nod"
    en: "point_name"
    jp: "測点名"

  point_number:
    drg-gps: "pointNumber"
    gyoroman-gg: "INDX"
    en: "point_number"
    jp: "測点番号"

  longitude:
    drg-gps: "lon"
    gyoroman-gg: "LON"
    en: "longitude"
    jp: "経度"

  latitude:
    drg-gps: "lat"
    gyoroman-gg: "LAT"
    en: "latitude"
    jp: "緯度"

  altitude:
    drg-gps: "ele"
    gyoroman-gg: "HEIGHT"
    en: "altitude"
    jp: "高度"

  ellipse_height:
    drg-gps: "ellipsoidHeight"
    en: "ellipse_height"
    jp: "楕円体高"

  geoid_height:
    drg-gps: "geoidheight"
    gyoroman-gg: "GEOIDH"
    en: "geoid_height"
    jp: "ジオイド高"

  fix:
    drg-gps: "fix"
    en: "fix"
    jp: "Fix"

  fix_mode:
    drg-gps: "fixMode"
    en: "fix_mode"
    jp: "FixMode"

  epochs:
    drg-gps: "epochs"
    gyoroman-gg: "DATAN"
    en: "epochs"
    jp: "測定回数"

  interval:
    drg-gps: "epochInterval"
    en: "interval[sec]"
    jp: "測定間隔[秒]"

  pdop:
    drg-gps: "pdop"
    gyoroman-gg: "PDOP"
    en: "pdop"
    jp: "PDOP"

  number_of_satellites:
    drg-gps: "sat"
    gyoroman-gg: "SATN"
    en: "number_of_satellites"
    jp: "衛星数"

  std_h:
    drg-gps: "stddevDistanceMeter"
    gyoroman-gg: "RMSX"
    en: "std_h"
    jp: "水平方向標準偏差"

  std_v:
    drg-gps: "stddevHeightMeter"
    gyoroman-gg: "RMSY"
    en: "std_v"
    jp: "鉛直方向標準偏差"

  signals:
    drg-gps: "signals"
    en: "signals"
    jp: "衛星信号"

  signal_frequencies:
    en: "signal_frequencies"
    jp: "周波数"

  receiver:
    drg-gps: "receiverName"
    en: "receiver"
    jp: "受信機"

  antenna:
    drg-gps: "antennaType"
    en: "antenna"
    jp: "アンテナ"

  jgd:
    drg-gps: "coordGenaration"
    en: "jgd"
    jp: "平面直角座標系"

  epsg:
    drg-gps: "type"
    en: "epsg"
    jp: "EPSG"

  transformed_y:
    drg-gps: "y"
    en: "transformed_Y"
    jp: "補正後Y"

  transformed_x:
    drg-gps: "x"
    en: "transformed_X"
    jp: "補正後X"

  office:
    en: "office"
    jp: "森林管理署"

  branch_office:
    en: "branch_office"
    jp: "森林事務所"

  local_area:
    en: "local_area"
    jp: "国有林"

  address:
    en: "address"
    jp: "林小班"

  project_year:
    en: "project_year"
    jp: "事業年度"

  project_name:
    en: "project_name"
    jp: "事業名"

  surveyor:
    en: "surveyor"
    jp: "測量者"

  group_name:
    en: "group_name"
    jp: "班名"

  label:
    en: "label"
    jp: "label"

  point_size:
    en: "point_size"
    jp: "point_size"

# データを利用する列名のリスト
use_cols_en:
  - sort_index
  - start
  - end
  - point
  - point_name
  - point_number
  - longitude
  - latitude
  - altitude
  - ellipsoid_height
  - geoid_height
  - antenna_height
  - fix
  - fix_mode
  - epochs
  - interval
  - pdop
  - number_of_satellites
  - std_h
  - std_v
  - signals
  - signal_frequencies
  - receiver
  - antenna
  - jgd
  - epsg
  - transformed_y
  - transformed_x
  - group_name
  - project_year
  - project_name
  - office
  - branch_office
  - local_area
  - address
  - surveyor
  - label
  - point_size