colors:
  blue: '#0000ff'
  gold: '#ffd700'
  green: '#008000'
  limegreen: '#32cd32'
  olive: '#008b8b'
  orange: '#ff8c00'
  pink: '#ff1493'
  red: '#dc143c'
  skyblue: '#00bfff'
  violet: '#8a2be2'
columns:
  add_cols:
    address:
      en: address
      jp: 林小班
    branch_office:
      en: branch_office
      jp: 森林事務所
    group_name:
      en: group_name
      jp: 班名
    label:
      en: label
      jp: label
    local_area:
      en: local_area
      jp: 国有林
    office:
      en: office
      jp: 森林管理署
    point:
      en: point
      jp: 測点
    point_size:
      en: point_size
      jp: point_size
    project_name:
      en: project_name
      jp: 事業名
    project_year:
      en: project_year
      jp: 事業年度
    signal_frequencies:
      en: signal_frequencies
      jp: 周波数
    surveyor:
      en: surveyor
      jp: 測量者
  drogger_gps:
    antennaHeightMesure:
      en: antenna_height
      jp: アンテナ高
    antennaType:
      en: antenna
      jp: アンテナ
    coordGenaration:
      en: jgd
      jp: 平面直角座標系
    ele:
      en: altitude
      jp: 高度
    ellipsoidHeight:
      en: ellipse_height
      jp: 楕円体高
    endtime:
      en: end
      jp: 終了
    epochInterval:
      en: interval[sec]
      jp: 測定間隔[秒]
    epochs:
      en: epochs
      jp: 測定回数
    fix:
      en: fix
      jp: Fix
    fixMode:
      en: fix_mode
      jp: FixMode
    geoidheight:
      en: geoid_height
      jp: ジオイド高
    hdop:
      en: pdop
      jp: PDOP
    lat:
      en: latitude
      jp: 緯度
    lon:
      en: longitude
      jp: 経度
    name:
      en: point_name
      jp: 測点名
    pdop:
      en: pdop
      jp: PDOP
    pointNumber:
      en: point_number
      jp: 測点番号
    receiverName:
      en: receiver
      jp: 受信機
    sat:
      en: number_of_satellites
      jp: 衛星数
    signals:
      en: signals
      jp: 衛星信号
    starttime:
      en: start
      jp: 開始
    stddevDistanceMeter:
      en: std_h
      jp: 水平方向標準偏差
    stddevHeightMeter:
      en: std_v
      jp: 鉛直方向標準偏差
    type:
      en: epsg
      jp: EPSG
    vdop:
      en: vdop
      jp: VDOP
    x:
      en: transformed_X
      jp: 補正後X
    y:
      en: transformed_Y
      jp: 補正後Y
  gyoroman_gg_csv:
    DATAN:
      en: epochs
      jp: 測定回数
    GEOIDH:
      en: geoid_height
      jp: ジオイド高
    HDOP:
      en: hdop
      jp: HDOP
    HEIGHT:
      en: altitude
      jp: 高度
    INDX:
      en: point_number
      jp: 測点番号
    LAT:
      en: latitude
      jp: 緯度
    LON:
      en: longitude
      jp: 経度
    Nod:
      en: point_name
      jp: 測点名
    PDOP:
      en: pdop
      jp: PDOP
    RMSX:
      en: std_h
      jp: 水平方向標準偏差
    RMSY:
      en: std_v
      jp: 鉛直方向標準偏差
    SATN:
      en: number_of_satellites
      jp: 衛星数
    SYSTIME:
      en: end
      jp: 終了
    VDOP:
      en: vdop
      jp: vdop
  selects:
    address: address
    altitude: altitude
    antenna: antenna
    branch_office: branch_office
    end: end
    epochs: epochs
    fix_mode: fix_mode
    group_name: group_name
    interval: interval
    latitude: latitude
    local_area: local_area
    longitude: longitude
    number_of_satellites: number_of_satellites
    office: office
    pdop: pdop
    point: point
    point_name: point_name
    point_number: point_number
    project_name: project_name
    project_year: project_year
    receiver: receiver
    signal_frequencies: signal_frequencies
    signals: signals
    sort_index: sort_index
    start: start
    surveyor: surveyor
  statistics:
    end:
      en: end
      jp: 終了
      stats: max
    epochs:
      en: epochs
      jp: 測定回数
      stats: mean
    interval:
      en: interval
      jp: 測定間隔
      stats: mean
    number_of_satellites:
      en: number_of_satellites
      jp: 衛星数
      stats: min
    pdop:
      en: pdop
      jp: PDOP
      stats: max
    receiver: null
    signal_frequencies:
      en: signal_frequencies
      jp: 周波数
      stats: unique_count
    signals:
      en: signals
      jp: 衛星信号
      stats: unique
    start:
      en: start
      jp: 開始
      stats: min
  use_cols_en:
  - sort_index
  - start
  - end
  - point
  - point_name
  - point_number
  - longitude
  - latitude
  - altitude
  - ellipsoid_height
  - geoid_height
  - antenna_height
  - fix
  - fix_mode
  - epochs
  - interval[sec]
  - pdop
  - number_of_satellites
  - std_h
  - std_v
  - signals
  - signal_frequencies
  - receiver
  - antenna
  - jgd
  - epsg
  - transformed_y
  - transformed_x
  - group_name
  - project_year
  - project_name
  - office
  - branch_office
  - local_area
  - address
  - surveyor
  - label
  - point_size
formats:
  datetime_format: '%Y-%m-%d %H:%M:%S'
  datetime_formats:
  - '%Y-%m-%dT%H:%M:%S.%f'
  - '%Y-%m-%d %H:%M:%S'
  - '%Y/%m/%d %H:%M:%S'
  - '%Y/%m/%d %H:%M'
  decimal_places:
    geodetic: 11
    mercator: 4
satellites:
  signals:
  - L1
  - L2
  - L5
  - L6
spatial_coordinates_system:
  JGD2011_R:
    JPN1: 6669
    JPN10: 6678
    JPN11: 6679
    JPN12: 6680
    JPN13: 6681
    JPN14: 6682
    JPN15: 6683
    JPN16: 6684
    JPN17: 6685
    JPN18: 6686
    JPN19: 6687
    JPN2: 6670
    JPN3: 6671
    JPN4: 6672
    JPN5: 6673
    JPN6: 6674
    JPN7: 6675
    JPN8: 6676
    JPN9: 6677
    UTM51: 6688
    UTM52: 6689
    UTM53: 6690
    UTM54: 6691
    UTM55: 6692
web:
  dummy: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0
  elevation: https://cyberjapandata2.gsi.go.jp/general/dem/scripts/getelevation.php?lon={}&lat={}&outtype=JSON
  semi_dynamic: http://vldb.gsi.go.jp/sokuchi/surveycalc/semidyna/web/semidyna_r.php?
